"""Exporters — convert tapes to various formats."""

from __future__ import annotations

from pathlib import Path

from agentvcr.tape import Tape


def export(tape: Tape, path: str | Path, format: str = "html") -> Path:
    """Export a tape to the given format.

    Supported formats: html, markdown, json, pytest
    """
    exporters = {
        "html": _export_html,
        "markdown": _export_markdown,
        "md": _export_markdown,
        "json": _export_json,
        "pytest": _export_pytest,
    }

    if format not in exporters:
        raise ValueError(f"Unknown format: {format}. Available: {', '.join(exporters)}")

    return exporters[format](tape, Path(path))


def _export_html(tape: Tape, path: Path) -> Path:
    """Export tape as a standalone HTML file with embedded viewer."""
    steps_html = ""
    for step in tape.steps:
        emoji = {"think": "🧠", "tool_call": "🔧", "observe": "👁️", "error": "❌",
                 "decision": "🔀", "retry": "🔄", "custom": "📌", "start": "▶️", "end": "⏹️"}.get(step.type.value, "•")
        bg = {"error": "#fee2e2", "tool_call": "#e0f2fe", "think": "#f0fdf4"}.get(step.type.value, "#f9fafb")
        steps_html += f"""
        <div class="step" style="background:{bg};padding:12px;margin:8px 0;border-radius:8px;border-left:4px solid #6366f1">
          <div style="display:flex;justify-content:space-between;align-items:center">
            <span>{emoji} <strong>{step.type.value}</strong> · Step {step.index + 1}</span>
            <span style="color:#888;font-size:0.85em">{step.timestamp_ms / 1000:.1f}s</span>
          </div>
          <p style="margin:8px 0 0">{step.content[:300]}</p>
          {"<details><summary>Details</summary><pre>" + str(step.input or "") + "\\n" + str(step.output or "")[:500] + "</pre></details>" if step.input or step.output else ""}
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>📼 AgentVCR — {tape.name or tape.session_id}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #fafafa; }}
    h1 {{ color: #1e1b4b; }}
    .meta {{ color: #666; font-size: 0.9em; margin-bottom: 20px; }}
    .stats {{ display: flex; gap: 16px; margin: 20px 0; }}
    .stat {{ background: white; padding: 12px 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
    .stat-value {{ font-size: 1.4em; font-weight: bold; color: #4f46e5; }}
    .stat-label {{ font-size: 0.8em; color: #888; }}
    pre {{ background: #1e1b4b; color: #e0e7ff; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 0.85em; }}
  </style>
</head>
<body>
  <h1>📼 {tape.name or 'Agent Session'}</h1>
  <div class="meta">Session: {tape.session_id} · Created: {tape.created_at}</div>
  <div class="stats">
    <div class="stat"><div class="stat-value">{tape.step_count}</div><div class="stat-label">Steps</div></div>
    <div class="stat"><div class="stat-value">{len(tape.tool_calls)}</div><div class="stat-label">Tool Calls</div></div>
    <div class="stat"><div class="stat-value">{len(tape.errors)}</div><div class="stat-label">Errors</div></div>
    <div class="stat"><div class="stat-value">{tape.duration_ms / 1000:.1f}s</div><div class="stat-label">Duration</div></div>
    <div class="stat"><div class="stat-value">{tape.total_tokens}</div><div class="stat-label">Tokens</div></div>
  </div>
  {steps_html}
  <footer style="margin-top:40px;text-align:center;color:#aaa;font-size:0.8em">
    Generated by 📼 AgentVCR v0.1.0
  </footer>
</body>
</html>"""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path


def _export_markdown(tape: Tape, path: Path) -> Path:
    """Export tape as Markdown."""
    lines = [
        f"# 📼 {tape.name or tape.session_id}",
        f"",
        f"- **Session**: {tape.session_id}",
        f"- **Duration**: {tape.duration_ms / 1000:.1f}s",
        f"- **Steps**: {tape.step_count}",
        f"- **Tool Calls**: {len(tape.tool_calls)}",
        f"- **Errors**: {len(tape.errors)}",
        f"- **Tokens**: {tape.total_tokens}",
        f"",
        f"## Steps",
        f"",
    ]

    for step in tape.steps:
        lines.append(f"### Step {step.index + 1}: {step.type.value} ({step.timestamp_ms / 1000:.1f}s)")
        lines.append("")
        if step.content:
            lines.append(step.content)
        if step.input:
            lines.append(f"\n**Input**: `{step.input}`")
        if step.output:
            lines.append(f"**Output**: `{str(step.output)[:200]}`")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _export_json(tape: Tape, path: Path) -> Path:
    """Export tape as JSON (same as save)."""
    return tape.save(path)


def _export_pytest(tape: Tape, path: Path) -> Path:
    """Export tape as pytest file."""
    from agentvcr.exporters.pytest_export import export_pytest

    return export_pytest(tape, path)
